name: proj0
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - backcall=0.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - decorator=5.2.1
  - executing=2.2.1
  - expat=2.7.3
  - importlib_metadata=8.5.0
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - ld_impl_linux-64=2.44
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libsodium=1.0.20
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.0.18
  - packaging=25.0
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.3
  - prompt-toolkit=3.0.52
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - python=3.9.25
  - python-dateutil=2.9.0post0
  - pyzmq=27.1.0
  - readline=8.3
  - setuptools=80.9.0
  - six=1.17.0
  - sqlite=3.51.0
  - stack_data=0.6.3
  - tk=8.6.15
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zlib=1.3.1
  - pip:
      - annotated-types==0.7.0
      - anyio==4.12.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - asttokens==3.0.1
      - async-lru==2.0.5
      - attrs==25.4.0
      - babel==2.17.0
      - beautifulsoup4==4.12.2
      - black==23.11.0
      - bleach==6.2.0
      - blinker==1.9.0
      - blis==0.7.11
      - catalogue==2.0.10
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.1.8
      - comm==0.2.3
      - confection==0.1.5
      - contourpy==1.3.0
      - cycler==0.12.1
      - cymem==2.0.13
      - debugpy==1.8.17
      - defusedxml==0.7.1
      - exceptiongroup==1.3.1
      - fastjsonschema==2.21.2
      - filelock==3.19.1
      - flask==3.0.0
      - flask-cors==4.0.0
      - flask-sqlalchemy==3.0.5
      - flask-wtf==1.1.1
      - fonttools==4.60.1
      - fqdn==1.5.1
      - fsspec==2025.10.0
      - greenlet==3.2.4
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.17.3
      - idna==3.11
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - iniconfig==2.1.0
      - ipykernel==6.25.2
      - ipython==8.18.1
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.1
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - joblib==1.3.2
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter==1.0.0
      - jupyter-console==6.6.3
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.5.0
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.7
      - langcodes==3.5.1
      - lark==1.3.1
      - markupsafe==3.0.3
      - matplotlib==3.7.2
      - matplotlib-inline==0.2.1
      - mistune==3.1.4
      - murmurhash==1.0.15
      - mypy-extensions==1.1.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nltk==3.8.1
      - notebook==7.5.0
      - notebook-shim==0.2.4
      - numpy==1.24.3
      - overrides==7.7.0
      - pandas==2.0.3
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pathlib-abc==0.1.1
      - pathspec==0.12.1
      - pathy==0.11.0
      - pillow==11.3.0
      - platformdirs==4.4.0
      - plotly==5.17.0
      - pluggy==1.6.0
      - preshed==3.0.12
      - prometheus-client==0.23.1
      - psutil==7.1.3
      - pycparser==2.23
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - pyparsing==3.0.9
      - pytest==7.4.3
      - python-dotenv==1.0.0
      - python-json-logger==4.0.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - qtconsole==5.7.0
      - qtpy==2.4.3
      - referencing==0.36.2
      - regex==2025.11.3
      - requests==2.31.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.27.1
      - safetensors==0.7.0
      - scikit-learn==1.3.0
      - scipy==1.10.1
      - seaborn==0.12.2
      - send2trash==1.8.3
      - smart-open==6.4.0
      - soupsieve==2.8
      - spacy==3.6.1
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - sqlalchemy==2.0.44
      - srsly==2.5.2
      - tenacity==9.1.2
      - terminado==0.18.1
      - thinc==8.1.12
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - tokenizers==0.14.1
      - tomli==2.3.0
      - tornado==6.5.2
      - tqdm==4.67.1
      - transformers==4.35.0
      - typer==0.9.4
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - uri-template==1.3.0
      - urllib3==2.5.0
      - wasabi==1.1.3
      - wcwidth==0.2.14
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - werkzeug==3.1.4
      - widgetsnbextension==4.0.15
      - wtforms==3.2.1
      - zipp==3.23.0
prefix: /home/adhni/miniconda3/envs/proj0
